### ISSUE TITLE
Advanced compilation broken

### ISSUE THREAD

**Issue by viebel** [immoh/lively-snake-demo#1]
`Lively` is great!

I'd like to know how to integrate it in my work flow.
Especially, I want to deploy my app in production with advanced compilation.
Obviously, I don't need lively in production.
But it seems that the `(:require lively)` statement breaks the compilation. Here is the compilation error:

``` bash
WARNING - incomplete alias created for namespace goog
if(cljs.core.truth_((function (){var and__3725__auto__ = goog;

```

I don't want to comment it out manually before each deployment.

What is the best way to keep the `(:require lively)` statement in the code?

**Comment by immoh** [comment]
I do it so that I require and init lively in a separate `dev` namespace which is located in different directory than my actual source files. This namespace is not required by any other namespace and I `goog.require` it in the development html source.

My development build (with no optimizations) includes this directory in source paths but my production build (advanced optimizations) doesn't. This ensures that no code related to lively goes to production code.

I could probably mention this in README and update the example project to use the same setup.

**Comment by viebel** [comment]
The problem is that `lively` is a dependency inside my `project.cljs` so it gets compiled and generates the warning.
Did I miss something?

**Comment by viebel** [comment]
Everything works fine. Thanks for your quick reply!
